# Generated by Django 4.2.7 on 2023-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_icon', models.CharField(max_length=100)),
                ('rest_name', models.CharField(max_length=100)),
                ('rest_description', models.TextField()),
            ],
        ),
    ]
