# Generated by Django 4.2.7 on 2023-11-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newww', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='rest_rating',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
    ]
