# Generated by Django 4.2.7 on 2023-11-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newww', '0002_data_rest_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='rest_image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
