# Generated by Django 4.2.7 on 2023-11-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newww', '0003_data_rest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(max_length=2)),
            ],
        ),
    ]
