# Generated by Django 4.2.7 on 2023-11-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newww', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
