# Generated by Django 4.2.7 on 2023-11-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newww', '0005_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_user_name', models.CharField(default='', max_length=100)),
                ('rest_name', models.CharField(default='', max_length=100)),
                ('rest_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rest_review', models.TextField()),
            ],
        ),
    ]
