# Generated by Django 4.2.7 on 2023-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newww', '0007_favrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_username', models.CharField(default='', max_length=100)),
                ('restname', models.CharField(default='', max_length=100)),
                ('restrating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('restreview', models.TextField()),
            ],
        ),
    ]
